version: '3.8'

services:
  funds_bot:
    build: .
    container_name: funds_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config/google-sheets-credentials.json:/app/config/google-sheets-credentials.json:ro